(() => {
  'use strict';

  const RELEASE = '20260809e';
  const URLS = {
    projects: `data/project-tracker.json?v=${RELEASE}`,
    news: `data/laboratory-news.json?v=${RELEASE}`,
    social: `data/social-intelligence.json?v=${RELEASE}`,
    benchmark: `data/public-demo-intelligence.json?v=${RELEASE}`,
    executive: `data/executive-public-intelligence.json?v=${RELEASE}`,
  };
  const state = { projects:null, news:null, social:null, benchmark:null, executive:null };
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp = v => Math.max(0, Math.min(100, Number(v) || 0));
  const THEMES = ['health system','digital','workflow','interoperability','analytics','ai','partnership','consumer','specialty','testing','stewardship','oncology','patient','data','access','innovation','genomic','genetic','automation'];

  function injectStyles(){
    if ($('#qExecutiveV2Styles')) return;
    const n=document.createElement('style'); n.id='qExecutiveV2Styles'; n.textContent=`
      .qv2-kicker{display:block;color:#35792a;font-size:11px;font-weight:700;letter-spacing:1.1px}.qv2-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;padding-bottom:10px;margin-bottom:12px;border-bottom:1px solid #d7e0d8}.qv2-head h3{margin:3px 0 0!important;color:#034c1f!important}.qv2-sub{font-size:9px;color:#646464}.qv2-grid{display:grid;gap:9px}.qv2-signal{display:grid;grid-template-columns:34px minmax(0,1fr) auto;gap:10px;align-items:start;padding:11px;border:1px solid #dce4dd;border-radius:8px;background:#fff}.qv2-signal-icon{width:32px;height:32px;border-radius:8px;display:grid;place-items:center;background:#edf4e9;color:#034c1f;font-weight:800}.qv2-signal strong{display:block;color:#202834;font-size:11px;line-height:1.35}.qv2-signal p{margin:4px 0;color:#646464;font-size:9px;line-height:1.45}.qv2-meta{display:flex;gap:6px;flex-wrap:wrap;color:#7b827d;font-size:8px}.qv2-tag{padding:3px 5px;border-radius:4px;background:#f2f6ef;color:#034c1f;font-weight:700}.qv2-link{white-space:nowrap;color:#034c1f;text-decoration:none;font-size:9px;font-weight:700}.qv2-link:hover{text-decoration:underline}
      .qv2-pmr-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-bottom:10px}.qv2-mini{border:1px solid #dce4dd;border-radius:7px;padding:8px;background:#fbfdfb}.qv2-mini span{display:block;font-size:8px;color:#646464}.qv2-mini strong{display:block;margin-top:3px;color:#034c1f;font-size:17px}.qv2-project{padding:9px 0;border-bottom:1px solid #e6ebe7}.qv2-project:last-child{border-bottom:0}.qv2-project-top{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.qv2-project strong{font-size:10px;color:#034c1f}.qv2-action{margin-top:4px;font-size:9px;color:#555}.qv2-project-meta{margin-top:4px;font-size:8px;color:#778078}.qv2-progress{height:6px;margin-top:6px;background:#e7ece8;border-radius:99px;overflow:hidden}.qv2-progress i{display:block;height:100%;background:linear-gradient(90deg,#034c1f,#35792a,#c6d52f)}.qv2-attention{padding:3px 6px;border-radius:4px;background:#fff1d4;color:#805600;font-size:8px;font-weight:700}.qv2-ontrack{background:#edf4e9;color:#034c1f}.qv2-footer{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:9px;padding-top:8px;border-top:1px solid #e3e8e4;color:#707871;font-size:8px}.qv2-button{border:0;background:transparent;color:#034c1f;font-weight:700;font-size:9px;cursor:pointer}
      .qv2-voice-insights{margin-top:12px;padding-top:11px;border-top:1px solid #dfe5e0}.qv2-voice-insights h4{margin:0 0 7px!important;color:#034c1f!important;font-size:11px!important}.qv2-voice-insights ul{margin:0;padding-left:17px;display:grid;gap:6px;color:#525b55;font-size:9px;line-height:1.45}.qv2-voice-insights strong{color:#034c1f}
      .qv2-activity-chart{display:grid;gap:7px}.qv2-bar-row{display:grid;grid-template-columns:115px minmax(80px,1fr) 28px;gap:7px;align-items:center;font-size:8px}.qv2-bar-row span:first-child{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.qv2-track{height:10px;background:#e8ede9;border-radius:3px;overflow:hidden}.qv2-track i{display:block;height:100%;background:linear-gradient(90deg,#034c1f,#35792a)}.qv2-social-list{display:grid;gap:6px;margin-top:11px;padding-top:10px;border-top:1px solid #dfe5e0}.qv2-social-item{padding:7px 8px;border-left:3px solid #c6d52f;background:#f8faf7;border-radius:0 6px 6px 0;font-size:8px;line-height:1.4;color:#555}.qv2-social-item strong{color:#034c1f}.qv2-note{margin-top:8px;color:#788079;font-size:8px;line-height:1.4}
      .qv2-benchmark-head{display:flex;gap:7px;flex-wrap:wrap;margin:5px 0 11px}.qv2-chip{padding:4px 7px;border-radius:5px;background:#edf4e9;color:#034c1f;font-size:8px;font-weight:700}.qv2-matrix-wrap{overflow:auto;border:1px solid #dce4dd;border-radius:8px}.qv2-matrix{width:100%;border-collapse:collapse;min-width:1050px;font-size:8px}.qv2-matrix th{background:#034c1f!important;color:#fff!important;padding:8px!important;text-align:center}.qv2-matrix th:first-child{text-align:left}.qv2-matrix td{padding:7px!important;text-align:center;border-bottom:1px solid #e8ece9!important}.qv2-matrix td:first-child{text-align:left;min-width:180px}.qv2-company strong{display:block;color:#034c1f;font-size:9px}.qv2-company small{display:block;color:#777;font-size:7px;margin-top:2px}.qv2-score{display:inline-grid;place-items:center;min-width:34px;height:25px;border-radius:5px;font-weight:800}.qv2-score.high{background:#dcebd4;color:#175d20}.qv2-score.mid{background:#f4f5d5;color:#676c00}.qv2-score.low{background:#fff1d4;color:#805600}.qv2-benchmark-highlights{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:9px}.qv2-benchmark-highlight{border:1px solid #dfe5e0;border-radius:7px;padding:8px;background:#fff}.qv2-benchmark-highlight strong{display:block;color:#034c1f;font-size:8px}.qv2-benchmark-highlight p{font-size:7px;color:#646464;line-height:1.4;margin:4px 0}.qv2-benchmark-highlight a{font-size:7px;color:#034c1f;font-weight:700;text-decoration:none}
      @media(max-width:1050px){.qv2-benchmark-highlights{grid-template-columns:repeat(2,1fr)}.qv2-pmr-summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){.qv2-signal{grid-template-columns:30px 1fr}.qv2-signal .qv2-link{grid-column:2}.qv2-benchmark-highlights{grid-template-columns:1fr}.qv2-bar-row{grid-template-columns:90px 1fr 24px}}
    `; document.head.appendChild(n);
  }

  async function loadData(){
    const entries=await Promise.all(Object.entries(URLS).map(async([k,u])=>{try{const r=await fetch(`${u}&refresh=${Date.now()}`,{cache:'no-store'});return [k,r.ok?await r.json():null]}catch(_){return[k,null]}}));
    entries.forEach(([k,v])=>{if(v)state[k]=v});
  }

  const homeView=()=>$('.view[data-view="home"],.view[data-view="executive"],.view[data-view="hub"],.view[data-view="dashboard"],.view[data-view="my-hub"]');
  const findPanel=(v,re)=>$$('.panel,.flo-panel,.q-ui-card',v).find(n=>re.test((n.textContent||'').replace(/\s+/g,' ')));
  const outstanding=p=>{const a=String(p?.next_step||'').trim().toLowerCase();return Boolean(a)&&!/no outstanding|completed final report|not applicable/.test(a)};
  const overdue=p=>{if(!outstanding(p)||!p?.milestone_due)return false;const d=new Date(`${p.milestone_due}T23:59:59Z`);return !Number.isNaN(d.valueOf())&&d<Date.now()};
  function metrics(){const p=state.projects?.projects||[];return{projects:p,open:p.filter(outstanding).length,pending:p.filter(x=>clamp(x.final_progress)<100).length,attention:p.filter(x=>overdue(x)||(x.risk&&!/^(na|n\/a|not applicable|none)$/i.test(String(x.risk).trim()))).length,onTrack:p.filter(x=>x.status==='On Track').length}}

  function replaceMetric(view,re,value,label){const t=$$('span,small,p,label',view).find(n=>re.test((n.textContent||'').trim()));if(!t)return;const p=t.parentElement;const v=p?.querySelector('strong,b')||t.previousElementSibling;if(v)v.textContent=String(value);t.textContent=label}
  function updateMetrics(view){const m=metrics();replaceMetric(view,/Potential search effort reduction/i,m.attention,'Executive attention items');replaceMetric(view,/Target KBQ turnaround/i,m.pending,'Final outputs pending');const c=$$('.flo-status-card',view).find(n=>/AI services/i.test(n.textContent||''));if(c)c.innerHTML=`<div class="flo-status-line"><i class="flo-dot"></i>Executive benchmark</div><strong>${state.benchmark?.companies?.length||0} companies</strong><small>Public-source + PMR alignment</small>`}

  function canonical(v=''){const t=String(v).toLowerCase();if(t.includes('quest'))return'Quest Diagnostics';if(t.includes('labcorp'))return'Labcorp';if(t.includes('arup'))return'ARUP Laboratories';if(t.includes('mayo'))return'Mayo Clinic Laboratories';if(t.includes('sonic'))return'Sonic Healthcare';return String(v||'Market')}
  function implication(i){const t=`${i.company||''} ${i.title||''} ${i.category||''}`.toLowerCase();if(/oncolog|genomic|genetic|mrd|cancer/.test(t))return'Review implications for advanced-diagnostics differentiation, specialty access and clinician workflow integration.';if(/partnership|collaboration|health system|hospital|epic|ehr/.test(t))return'Assess implications for health-system partnerships, interoperability and enterprise account strategy.';if(/consumer|at-home|ondemand|patient access/.test(t))return'Track consumer-access implications and opportunities to simplify the diagnostic journey.';if(/research|publication|stewardship|clinical evidence/.test(t))return'Consider how evidence, stewardship and expert-led differentiation can strengthen value propositions.';return'Review for commercial, portfolio or operating-model implications relevant to current Quest workstreams.'}
  function signals(){const a=(state.executive?.updates||[]).map(x=>({...x,source:'Official public source'}));const b=(state.news?.items||[]).slice(0,30).map(x=>({company:canonical(x.company),date:x.published_at||x.published_display||'',category:x.category||'Market update',title:x.title,summary:x.description||'',executive_implication:implication(x),url:x.url,source:x.source||'Internet monitor'}));const seen=new Set();return[...a,...b].filter(x=>x.title&&x.url).filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(seen.has(k))return false;seen.add(k);return true}).sort((x,y)=>String(y.date).localeCompare(String(x.date)))}
  const sigIcon=c=>/growth|capital|financial/i.test(c)?'↗':/specialty|genetic|oncolog/i.test(c)?'✦':/research|evidence/i.test(c)?'✓':'!';
  function renderSignals(view){const p=findPanel(view,/SIGNAL MONITOR|What changed since the last approved refresh|What changed in the latest public-source refresh/i);if(!p)return;const s=signals().slice(0,5);const sig=s.map(x=>`${x.date}|${x.title}`).join('||');if(p.dataset.qv2Sig===sig&&p.querySelector('.qv2-signal'))return;p.dataset.qv2Sig=sig;p.innerHTML=`<div class="qv2-head"><div><span class="qv2-kicker">SIGNAL MONITOR</span><h3>What changed in the latest public-source refresh?</h3><div class="qv2-sub">Verified company sources + current internet news monitor</div></div><span class="qv2-sub">${esc(state.executive?.generated_at?.slice(0,10)||'')}</span></div><div class="qv2-grid">${s.map(x=>`<article class="qv2-signal"><div class="qv2-signal-icon">${sigIcon(x.category||'')}</div><div><strong>${esc(x.title)}</strong><p>${esc(x.executive_implication||x.summary)}</p><div class="qv2-meta"><span class="qv2-tag">${esc(x.company)}</span><span>${esc(x.category||'Update')}</span><span>${esc(String(x.date||'').slice(0,10))}</span><span>${esc(x.source||'')}</span></div></div><a class="qv2-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open source ↗</a></article>`).join('')}</div>`}

  function shortName(p){const n=String(p?.project_name||'Workstream');if(/Digital Customer Journey/i.test(n))return p?.research_type?.includes('Survey')?'Digital Journey Survey':'Digital Journey IDIs';if(/Extended Study/i.test(n))return'Data Ecosystem Extended';if(/Data Ecosystem Needs/i.test(n))return'Data Ecosystem Needs';if(/Lab Stewardship/i.test(n))return'Lab Stewardship & Analytics';if(/Consumer Testing/i.test(n))return'Consumer Testing Profiles';if(/Health System Experience/i.test(n))return'Health System Experience';return n}
  function renderPmr(view){const e=$('#qExecutiveActions',view)||findPanel(view,/EXECUTIVE ATTENTION|Priority workstream actions|PMR DELIVERY & EXECUTIVE ACTIONS/i);const old=findPanel(view,/PMR PORTFOLIO|Active project health/i);if(!e)return;if(old&&old!==e)old.style.display='none';const m=metrics();const ps=[...m.projects].sort((a,b)=>Number(overdue(b))-Number(overdue(a))||clamp(a.final_progress)-clamp(b.final_progress));const sig=ps.map(p=>`${p.id}|${p.final_progress}|${p.next_step}|${p.milestone_due}|${p.status}`).join('||');if(e.dataset.qv2Sig===sig&&e.querySelector('.qv2-pmr-summary'))return;e.dataset.qv2Sig=sig;e.innerHTML=`<div class="qv2-head"><div><span class="qv2-kicker">PMR DELIVERY & EXECUTIVE ACTIONS</span><h3>Project progress and next actions</h3></div><span class="qv2-sub">Tracker ${esc(state.projects?.reporting_date||'')}</span></div><div class="qv2-pmr-summary"><div class="qv2-mini"><span>Workstreams</span><strong>${m.projects.length}</strong></div><div class="qv2-mini"><span>Open actions</span><strong>${m.open}</strong></div><div class="qv2-mini"><span>Final outputs pending</span><strong>${m.pending}</strong></div><div class="qv2-mini"><span>On track</span><strong>${m.onTrack}</strong></div></div>${ps.map(p=>{const a=overdue(p)||(p.risk&&!/^(na|n\/a|not applicable|none)$/i.test(String(p.risk).trim()));return`<article class="qv2-project"><div class="qv2-project-top"><strong>${esc(shortName(p))}</strong><span class="qv2-attention ${a?'':'qv2-ontrack'}">${a?'Action':esc(p.status||'On track')}</span></div><div class="qv2-action">${esc(p.next_step||p.next_milestone||'No outstanding action recorded.')}</div><div class="qv2-project-meta">${clamp(p.final_progress)}% final output · ${p.milestone_due?`Due ${esc(p.milestone_due)} · `:''}Owner: ${esc(p.next_step_owner||p.evs_lead||'Evalueserve')}</div><div class="qv2-progress"><i style="width:${clamp(p.final_progress)}%"></i></div></article>`}).join('')}<div class="qv2-footer"><span>Progress and actions come from the shared PMR tracker.</span><button class="qv2-button" type="button" data-qv2-tracker>Open Project Tracker →</button></div>`;$('[data-qv2-tracker]',e)?.addEventListener('click',()=>navigate(/Project Tracker/i))}

  function renderVoice(view){const p=findPanel(view,/VOICE OF EXPERTS|Top unmet needs/i);if(!p||p.querySelector('.qv2-voice-insights'))return;const b=document.createElement('div');b.className='qv2-voice-insights';b.innerHTML=`<h4>Executive attention</h4><ul><li><strong>Workflow integration:</strong> Digital Journey and Data Ecosystem workstreams center on interoperability, onboarding friction and fitting diagnostics into clinical workflows.</li><li><strong>Stewardship and decision support:</strong> Lab Stewardship points to continued demand for evidence-backed guidance that turns laboratory data into utilization decisions.</li><li><strong>Experience consistency:</strong> Health-system and consumer projects keep data consistency, simpler access and flexible service models on the executive agenda.</li></ul>`;p.appendChild(b)}

  function activityCounts(){const names=(state.benchmark?.companies||[]).map(x=>canonical(x.name));const c=Object.fromEntries(names.map(n=>[n,0]));(state.news?.items||[]).forEach(x=>{const n=canonical(x.company);if(n in c)c[n]+=1});(state.executive?.updates||[]).forEach(x=>{const n=canonical(x.company);if(n in c)c[n]+=1});return c}
  function renderMarket(view){const p=findPanel(view,/NEWS\s*&\s*SOCIAL|Market pulse|PUBLIC & SOCIAL ACTIVITY/i);if(!p)return;const c=activityCounts();const rows=Object.entries(c).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...rows.map(x=>x[1]));const social=[...(state.social?.companies||[])].sort((a,b)=>Number(b.momentum||0)-Number(a.momentum||0)).slice(0,3);const sig=JSON.stringify([rows,social.map(x=>[x.name,x.momentum,x.top_theme])]);if(p.dataset.qv2Sig===sig&&p.querySelector('.qv2-activity-chart'))return;p.dataset.qv2Sig=sig;p.innerHTML=`<div class="qv2-head"><div><span class="qv2-kicker">PUBLIC & SOCIAL ACTIVITY</span><h3>Company activity pulse</h3></div><span class="qv2-sub">Current internet feed</span></div><div class="qv2-activity-chart">${rows.map(([n,v])=>`<div class="qv2-bar-row"><span>${esc(n)}</span><span class="qv2-track"><i style="width:${Math.max(4,Math.round(v/max*100))}%"></i></span><b>${v}</b></div>`).join('')}</div><div class="qv2-social-list">${social.map(x=>{const post=x.posts_summary?.[0];return`<div class="qv2-social-item"><strong>${esc(x.name)} · ${esc(x.top_theme||'Social theme')}</strong><br>${esc(post?.summary||'No recent social summary available.')}</div>`}).join('')}</div><div class="qv2-note">Bars count current public-news records plus the latest verified public-source highlight. Social highlights come from the connected social dataset (${esc(state.social?.status||'unknown')}).</div>`}

  const companySocial=n=>(state.social?.companies||[]).find(x=>canonical(x.name)===n);
  const companyHighlight=n=>(state.executive?.updates||[]).find(x=>canonical(x.company)===n);
  const companyNews=n=>(state.news?.items||[]).filter(x=>canonical(x.company)===n).slice(0,20);
  function pmrScore(n,b){const pt=(state.projects?.projects||[]).map(x=>`${x.project_name} ${x.sow_focus} ${x.next_step}`).join(' ').toLowerCase();const s=companySocial(n),h=companyHighlight(n);const ct=[b?.facts?.join(' '),s?.top_theme,s?.posts_summary?.map(x=>`${x.theme} ${x.summary}`).join(' '),h?.title,h?.summary,companyNews(n).map(x=>`${x.title} ${x.description}`).join(' ')].join(' ').toLowerCase();const active=THEMES.filter(t=>pt.includes(t));return clamp(35+active.filter(t=>ct.includes(t)).length*7)}
  function socialScore(n){const all=state.social?.companies||[],x=companySocial(n);if(!x||!all.length)return 0;const mp=Math.max(1,...all.map(i=>Number(i.posts||0))),me=Math.max(1,...all.map(i=>Number(i.engagement_rate||0))),mm=Math.max(1,...all.map(i=>Number(i.momentum||0)));return clamp(Number(x.posts||0)/mp*45+Number(x.engagement_rate||0)/me*35+Number(x.momentum||0)/mm*20)}
  const scoreClass=s=>s>=80?'high':s>=60?'mid':'low';const scoreCell=s=>{const v=Math.round(clamp(s));return`<span class="qv2-score ${scoreClass(v)}">${v}</span>`};
  function renderBenchmark(view){const p=$('#qExecutiveDecisionMap',view)||findPanel(view,/EXECUTIVE DECISION MAP|Live workstream readiness and attention|EXECUTIVE COMPETITIVE BENCHMARK/i);if(!p||!(state.benchmark?.companies||[]).length)return;const counts=activityCounts(),max=Math.max(1,...Object.values(counts));const rows=state.benchmark.companies.map(b=>{const n=canonical(b.name),q=b.benchmark||{};return{b,n,scale:q.enterprise_scale,reach:q.clinical_reach,specialty:q.specialty_depth,digital:q.digital_access,global:q.global_reach,activity:clamp((counts[n]||0)/max*100),social:socialScore(n),pmr:pmrScore(n,b)}});const sig=JSON.stringify(rows.map(r=>[r.n,r.scale,r.reach,r.specialty,r.digital,r.global,Math.round(r.activity),Math.round(r.social),Math.round(r.pmr)]));if(p.dataset.qv2Sig===sig&&p.querySelector('.qv2-matrix'))return;p.dataset.qv2Sig=sig;p.innerHTML=`<div class="qv2-head"><div><span class="qv2-kicker">EXECUTIVE COMPETITIVE BENCHMARK</span><h3>Company benchmark across public-source strength and PMR relevance</h3></div><button class="secondary-button" type="button" data-qv2-refresh>↻ Refresh data</button></div><div class="qv2-benchmark-head"><span class="qv2-chip">${rows.length} companies</span><span class="qv2-chip">8 parameters</span><span class="qv2-chip">Public facts + internet activity + social data + PMR themes</span></div><div class="qv2-matrix-wrap"><table class="qv2-matrix"><thead><tr><th>Company</th><th>Enterprise scale</th><th>Clinical reach</th><th>Specialty depth</th><th>Digital access</th><th>Global reach</th><th>Recent public activity</th><th>Social activity</th><th>PMR alignment</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="qv2-company"><strong>${esc(r.n)}</strong><small>${esc(r.b.scale_headline||'')}</small></td><td>${scoreCell(r.scale)}</td><td>${scoreCell(r.reach)}</td><td>${scoreCell(r.specialty)}</td><td>${scoreCell(r.digital)}</td><td>${scoreCell(r.global)}</td><td>${scoreCell(r.activity)}</td><td>${scoreCell(r.social)}</td><td>${scoreCell(r.pmr)}</td></tr>`).join('')}</tbody></table></div><div class="qv2-benchmark-highlights">${rows.map(r=>{const h=companyHighlight(r.n);return`<article class="qv2-benchmark-highlight"><strong>${esc(r.n)}</strong><p>${esc(h?.executive_implication||h?.summary||'Public-source baseline available.')}</p><a href="${esc(h?.url||r.b.source||'#')}" target="_blank" rel="noopener noreferrer">Source ↗</a></article>`}).join('')}</div><div class="qv2-note">The first five parameters are directional normalized indices attached to verified public-source facts. Public activity is calculated from the internet news feed, social activity from the connected social dataset, and PMR alignment from keyword overlap with current Quest workstream themes.</div>`;$('[data-qv2-refresh]',p)?.addEventListener('click',async()=>{await loadData();apply()})}

  function navigate(re){const n=$$('.nav-item').find(x=>re.test(x.textContent||''));n?.click()}
  function apply(){const v=homeView();if(!v)return;updateMetrics(v);renderSignals(v);renderPmr(v);renderVoice(v);renderMarket(v);renderBenchmark(v)}
  async function boot(){injectStyles();await loadData();apply();setTimeout(apply,1500);setTimeout(apply,4000);window.addEventListener('quest:layout-refresh',()=>setTimeout(apply,120));window.addEventListener('quest:module-loaded',()=>setTimeout(apply,120));document.addEventListener('click',e=>{if(e.target.closest?.('.nav-item,#floHomeRefresh'))setTimeout(apply,1000)},true);setInterval(apply,30000);setInterval(async()=>{await loadData();apply()},5*60*1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();