(() => {
  'use strict';
  const RELEASE='20260901stable1';
  const loaded=new Map(),groupLoads=new Map();
  const GROUPS={alerts:[],competitor:[],strategic:[],insights:['integrations/enterprise-insights-engine/loader.js','integrations/insights-engine-layout-v3.js','integrations/insights-engine-evidence-placement-final.js','integrations/quest-enterprise-insights-override.js'],library:['integrations/knowledge-repository-lite.js'],pmr:['integrations/pmr-repository-dashboard-final.js'],experts:['integrations/voice-experts-dashboard-final.js'],survey:['integrations/survey-analytics-dashboard-final.js'],governance:['integrations/no-cost-live-operations.js','integrations/live-governance-panels.js'],microsoft:['integrations/local-file-extraction.js','integrations/microsoft-local-bridge.js','integrations/microsoft-security-guard.js','integrations/approved-insights-panel.js']};
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
  function cleanup(){document.querySelectorAll('.nav-item').forEach(n=>{if(/^competitive landscape$/i.test(clean(n.textContent)))n.remove()});document.querySelectorAll('.view[data-view]').forEach(v=>{const h=clean(v.querySelector('h1,h2,h3,[class*="title"]')?.textContent);if(v.dataset.view==='landscape'||/competitive landscape/i.test(h))v.remove()})}
  function progress(active,done=false){let n=document.getElementById('qModuleProgress');if(!n){n=document.createElement('div');n.id='qModuleProgress';n.className='q-module-progress';n.innerHTML='<i></i>';document.body.appendChild(n)}n.classList.toggle('active',!!active);n.classList.toggle('done',!!done);if(done)setTimeout(()=>n.remove(),220)}
  function loadScript(path){if(loaded.has(path))return loaded.get(path);const existing=[...document.scripts].find(s=>(s.src||'').includes(path));if(existing){const p=Promise.resolve(existing);loaded.set(path,p);return p}const p=new Promise((res,rej)=>{const s=document.createElement('script');s.src=new URL(`${path}?v=${RELEASE}`,document.baseURI).href;s.async=true;s.onload=()=>{window.dispatchEvent(new CustomEvent('quest:module-loaded',{detail:{path}}));res(s)};s.onerror=()=>rej(new Error(`Unable to load ${path}`));document.body.appendChild(s)});loaded.set(path,p);return p}
  async function loadGroup(name){if(!GROUPS[name]||!GROUPS[name].length)return;if(groupLoads.has(name))return groupLoads.get(name);const p=(async()=>{progress(true);try{for(const path of GROUPS[name])await loadScript(path)}catch(e){console.error(`Quest ${name} module load failed:`,e)}finally{progress(false,true);window.dispatchEvent(new CustomEvent('quest:layout-refresh',{detail:{group:name}}))}})();groupLoads.set(name,p);return p}
  function groupFromText(v=''){const t=String(v).toLowerCase();if(/alert|strategic signal/.test(t))return'alerts';if(/competitor profile/.test(t))return'competitor';if(/news intelligence|strategic analysis|social|perception/.test(t))return'strategic';if(/insights engine|insights copilot|ask insights/.test(t))return'insights';if(/voice of experts|persona intelligence|expert analysis/.test(t))return'experts';if(/survey analytics|survey intelligence/.test(t))return'survey';if(/knowledge repository|research repository|evidence library/.test(t))return'library';if(/pmr projects|pmr reports|primary market research/.test(t))return'pmr';if(/microsoft|sharepoint|local data|local repository|local file/.test(t))return'microsoft';if(/project tracker|methodology|audit/.test(t))return'governance';return''}
  function groupFromElement(t){const n=t?.closest?.('.nav-item,[data-view],a,button');return n?groupFromText(`${n.dataset?.view||''} ${n.textContent||''}`):''}
  async function bootCore(){progress(true);try{cleanup();for(const p of ['integrations/chart-lite.js','integrations/role-access-governance.js','integrations/quest-brand-system.js','integrations/frontend-performance-layout.js','integrations/frontend-readability-overrides.js','integrations/frontend-stability-guard.js','integrations/local-data-fetch-bridge.js','integrations/executive-status-seed.js','integrations/executive-hub-final.js','integrations/executive-insight-split-layout.js','integrations/knowledge-repository-lite.js','integrations/knowledge-legacy-guard.js','integrations/public-demo-evidence.js','integrations/executive-typography-benchmark-cleanup.js','integrations/pmr-repository-dashboard-final.js','integrations/voice-experts-dashboard-final.js','integrations/survey-analytics-dashboard-final.js','integrations/chart-alignment-system.js','integrations/frontend-quality-guard.js'])await loadScript(p)}catch(e){console.error('Quest core load failed:',e)}finally{progress(false,true)}}
  function bind(){document.addEventListener('click',e=>{const g=groupFromElement(e.target);if(g)loadGroup(g)},false);window.addEventListener('hashchange',()=>{const active=document.querySelector('.nav-item.active,[aria-current="page"],[data-view].active');const g=groupFromText(`${active?.dataset?.view||''} ${active?.textContent||''}`);if(g)loadGroup(g)})}
  async function boot(){cleanup();bind();await bootCore();document.documentElement.dataset.questRelease=RELEASE;document.documentElement.classList.add('quest-ready')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();